// web/src/src/views/Home.vue
<template>
  <div class="home">
    <div class="auth-wrapper">
      <auth v-if="!token && !hasGrantData" />
      <pin v-if="token && token.isExpired() || !token && hasGrantData" />
    </div>
    <transactions v-if="token && !token.isExpired()" />
  </div>
</template>

<script lang="ts">
import { mapState } from 'vuex';
import { Component, Vue } from 'vue-property-decorator';
import Auth from '@/components/Auth.vue';
import Pin from '@/components/Pin.vue';
import Transactions from '@/components/Transactions.vue';
import {
  State,
  Getter,
} from 'vuex-class';
import { Token } from '../types';

@Component({
  components: {
    Auth,
    Pin,
    Transactions,
  },
})
export default class Home extends Vue {
  @State('token') token: Token;
  @Getter('hasGrantData') hasGrantData: boolean;
}
</script>

<style scoped lang="less">
.auth-wrapper {
    position: absolute;
    top: 50%;
    left: 50%;
}
</style>

// web/src/views/Home.tsx
import { observer } from 'mobx-react';
import { RootStore } from '../store';
import * as React from 'react';
import Auth from '../components/Auth';
import Pin from '../components/Pin';
import Transactions from '../components/Transactions';
import * as style from './Home.scss';

@observer
export class Home extends React.Component<{store: RootStore}, {}> {
  render() {
    const store = this.props.store;
    return (
      <div className="home">
      {!store.token || store.token.isExpired() ? (
        <div className={style['auth-wrapper']}>
          {!store.token && !store.hasGrantData && <Auth store={store} />}
          {store.token && store.token.isExpired() || !store.token && store.hasGrantData && <Pin store={store} />}
        </div>
      ) : (<Transactions store={store} />)}
      </div>
    );
  }
}
