// web/src_vuejs/src/components/Loader.vue
<template>
    <img class="loader" src="https://loading.io/spinners/google/index.svg" />
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class Loader extends Vue {}
</script>

<style scoped lang="less">
.loader {
    position: absolute;
    top: 50%;
    left: 50%;
    z-index: 1;
}
</style>

// web/src_react/src/components/Loader.tsx
import * as React from "react";

export default class extends React.Component<{}, {}> {
  render() {
    return <img className="loader" src="https://loading.io/spinners/google/index.svg" />;
  }
}

{/* <style scoped lang="less">
.loader {
    position: absolute;
    top: 50%;
    left: 50%;
    z-index: 1;
}
</style> */}
